import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, CreditCard, MessageCircle, QrCode, ShieldCheck, UserCircle2 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { DropHeader } from "@/components/drop-header";
import { plans } from "@/lib/drop-data";
import aboutImage from "@/assets/drop-about.jpg";

export const Route = createFileRoute("/assinar")({
  validateSearch: (search: Record<string, unknown>) => ({ plano: typeof search.plano === "string" ? search.plano : "corte" }),
  head: () => ({ meta: [
    { title: "Assinar Clube DROP | DROP Barbearia" }, { name: "description", content: "Escolha seu plano mensal de corte e barba na DROP Barbearia." },
    { property: "og:title", content: "Clube DROP | Estilo em dia todo mês" }, { property: "og:description", content: "Planos de corte e barba a partir de R$ 35 por mês." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: SubscribePage,
});

function SubscribePage(){
  const {plano}=Route.useSearch(); const [step,setStep]=useState(0); const [plan,setPlan]=useState(plans.some(p=>p.id===plano)?plano:"corte"); const [payment,setPayment]=useState<"pix"|"card"|"">(""); const [avatar,setAvatar]=useState(0); const [form,setForm]=useState({nome:"",sobrenome:"",cpf:"",cep:"",rua:"",numero:"",complemento:"",cidade:"Cachoeiro de Itapemirim",bairro:"",estado:"ES",senha:"",telefone:""});
  const selectedPlan=plans.find(p=>p.id===plan)??plans[0]; const validForm=Object.entries(form).filter(([k])=>!['complemento'].includes(k)).every(([,v])=>v.trim().length>1);
  const next=()=>setStep(s=>Math.min(7,s+1)); const back=()=>setStep(s=>Math.max(0,s-1));
  const fields: [keyof typeof form,string,string][]=[["nome","Nome","text"],["sobrenome","Sobrenome","text"],["cpf","CPF","text"],["telefone","WhatsApp","tel"],["cep","CEP","text"],["rua","Rua","text"],["numero","Número","text"],["complemento","Complemento (opcional)","text"],["bairro","Bairro","text"],["cidade","Cidade","text"],["estado","Estado","text"]];
  return <div className="min-h-screen"><DropHeader/><main className="mx-auto max-w-6xl px-4 pb-16 pt-24 sm:px-6 lg:pt-28"><div className="mb-6 flex justify-between"><Link to="/" className="flex items-center gap-2 text-xs font-bold uppercase text-muted-foreground"><ArrowLeft className="h-4 w-4"/> Voltar ao site</Link>{step<7&&<span className="text-xs font-bold uppercase text-muted-foreground">Etapa {step+1} de 7</span>}</div><div className="mb-6 grid grid-cols-7 gap-1.5">{[0,1,2,3,4,5,6].map(i=><div key={i} className={`h-1 ${i<=step?'bg-primary':'bg-muted'}`}/>)}</div><section className="glass min-h-[680px] overflow-hidden border border-line">
    {step===0&&<div className="grid min-h-[680px] md:grid-cols-[.9fr_1.1fr]"><img src={aboutImage} alt="Clube DROP" width="1024" height="1280" className="h-80 w-full object-cover md:h-full"/><div className="flex flex-col justify-center p-7 sm:p-12"><p className="eyebrow">Clube DROP</p><h1 className="mt-5 font-display text-4xl uppercase leading-none sm:text-6xl">Seu estilo não tira folga.</h1><p className="mt-6 max-w-lg text-muted-foreground">Faça parte do clube e mantenha corte e barba sempre em dia, com economia e prioridade.</p><Button onClick={next} size="lg" className="mt-9 w-fit">Escolher meu plano <ArrowRight/></Button></div></div>}
    {step===1&&<Flow title="Escolha seu ritmo." eyebrow="Planos Clube DROP"><div className="grid gap-3 md:grid-cols-2">{plans.map(p=><button key={p.id} onClick={()=>setPlan(p.id)} className={`choice-card ${plan===p.id?'choice-card-active':''}`}><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-4"><div><p className="font-bold uppercase">{p.name}</p><p className="mt-1 text-xs text-muted-foreground">{p.label}</p></div><p className="font-display text-xl text-primary">R$ {p.price}</p></div><ul className="mt-4 space-y-1 text-xs text-muted-foreground">{p.services.slice(0,3).map(s=><li key={s}>• {s}</li>)}</ul></button>)}</div></Flow>}
    {step===2&&<Flow title="Conte sobre você." eyebrow="Dados pessoais e endereço"><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key,label,type])=><label key={key} className={key==='rua'||key==='complemento'?'sm:col-span-2':''}><span className="mb-2 block text-xs font-bold uppercase text-muted-foreground">{label}</span><Input type={type} maxLength={key==='cpf'?14:100} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="h-12 bg-background/50"/></label>)}</div></Flow>}
    {step===3&&<Flow title="Sua conta, do seu jeito." eyebrow="Segurança e comunicação"><div className="grid gap-4 md:grid-cols-2"><div className="choice-card"><ShieldCheck className="text-primary"/><h3 className="mt-5 font-bold uppercase">Segurança da conta</h3><p className="mt-2 text-sm text-muted-foreground">Crie uma senha para acessar seus dados e próximos agendamentos.</p><Input type="password" placeholder="Mínimo de 8 caracteres" minLength={8} value={form.senha} onChange={e=>setForm({...form,senha:e.target.value})} className="mt-5 h-12"/></div><div className="choice-card choice-card-active"><MessageCircle className="text-primary"/><h3 className="mt-5 font-bold uppercase">Automação via WhatsApp</h3><p className="mt-2 text-sm text-muted-foreground">Você receberá confirmações, lembretes e avisos importantes diretamente no seu WhatsApp.</p><div className="mt-5 flex items-center gap-3 text-sm text-success"><Check className="h-5 w-5"/> Ativado para seu número</div></div></div></Flow>}
    {step===4&&<Flow title="Escolha sua presença." eyebrow="Foto de perfil"><div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{["DM","RX","JV","TS"].map((a,i)=><button key={a} onClick={()=>setAvatar(i)} className={`choice-card flex aspect-square flex-col items-center justify-center ${avatar===i?'choice-card-active':''}`}><div className="grid h-20 w-20 place-items-center rounded-full bg-secondary font-display text-2xl text-primary">{a}</div><p className="mt-4 text-xs font-bold uppercase">Avatar {i+1}</p></button>)}</div><Button variant="outline" className="mt-6"><UserCircle2/> Enviar minha foto</Button></Flow>}
    {step===5&&<Flow title="Como prefere pagar?" eyebrow="Forma de pagamento"><div className="grid gap-4 md:grid-cols-2"><button onClick={()=>setPayment('pix')} className={`choice-card min-h-48 ${payment==='pix'?'choice-card-active':''}`}><QrCode className="h-8 w-8 text-primary"/><h3 className="mt-8 font-display text-2xl uppercase">PIX</h3><p className="mt-2 text-sm text-muted-foreground">Aprovação rápida e segura.</p></button><button onClick={()=>setPayment('card')} className={`choice-card min-h-48 ${payment==='card'?'choice-card-active':''}`}><CreditCard className="h-8 w-8 text-primary"/><h3 className="mt-8 font-display text-2xl uppercase">Cartão</h3><p className="mt-2 text-sm text-muted-foreground">Crédito ou débito recorrente.</p></button></div></Flow>}
    {step===6&&<Flow title="Último passo." eyebrow="Pagamento"><div className="grid gap-8 md:grid-cols-2"><div>{payment==='pix'?<div className="choice-card text-center"><div className="mx-auto grid aspect-square max-w-56 grid-cols-7 gap-1 bg-foreground p-4">{Array.from({length:49},(_,i)=><span key={i} className={(i*7+i*3)%5<2?'bg-background':'bg-foreground'}/>)}</div><p className="mt-5 font-bold">Escaneie para pagar R$ {selectedPlan.price}</p><p className="mt-2 text-xs text-muted-foreground">Código válido por 15 minutos.</p></div>:<div className="space-y-4"><Input placeholder="Número do cartão" maxLength={19} className="h-12"/><div className="grid grid-cols-2 gap-4"><Input placeholder="MM/AA" maxLength={5} className="h-12"/><Input placeholder="CVV" maxLength={4} className="h-12"/></div><Input placeholder="Nome impresso no cartão" maxLength={100} className="h-12"/></div>}</div><div className="border border-primary bg-primary/5 p-6"><p className="eyebrow">Resumo</p><h3 className="mt-4 font-display text-2xl uppercase">{selectedPlan.name}</h3><p className="mt-5 font-display text-5xl">R$ {selectedPlan.price}</p><p className="text-sm text-muted-foreground">por mês · vigência indeterminada</p></div></div></Flow>}
    {step===7&&<div className="flex min-h-[680px] flex-col items-center justify-center p-7 text-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-success text-primary-foreground"><Check className="h-9 w-9"/></div><p className="eyebrow mt-8">Bem-vindo ao Clube DROP</p><h1 className="mt-4 max-w-2xl font-display text-4xl uppercase leading-none sm:text-6xl">Seu estilo agora é prioridade.</h1><p className="mt-6 max-w-md text-muted-foreground">Assinatura confirmada. Você receberá todos os detalhes e próximos passos no WhatsApp.</p><Button asChild size="lg" className="mt-9"><Link to="/agendar">Agendar meu primeiro horário</Link></Button></div>}
    {step>0&&step<7&&<div className="flex justify-between border-t border-line px-5 py-5 sm:px-10"><Button variant="ghost" onClick={back}><ChevronLeft/> Voltar</Button><Button onClick={next} disabled={(step===2&&!validForm)||(step===3&&form.senha.length<8)||(step===5&&!payment)}>{step===6?'Confirmar assinatura':'Próximo'} <ArrowRight/></Button></div>}
  </section></main></div>;
}

function Flow({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <div className="min-h-[590px] p-6 sm:p-10 lg:p-14"><p className="eyebrow">{eyebrow}</p><h1 className="mt-4 font-display text-3xl uppercase sm:text-5xl">{title}</h1><div className="mt-9">{children}</div></div>}